// <auto-generated />
namespace Bridge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class df3wwasse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(df3wwasse));
        
        string IMigrationMetadata.Id
        {
            get { return "201708201739023_df3wwasse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
